In [1]:
import pandas as pd
import numpy as np
import torch
from torch import nn


In [ ]:
emb = nn.ModuleDict(
    {"a": nn.Embedding(10, 3), "b": nn.Embedding(10, 3)}
)


isinstance(emb, nn.ModuleDict)
for k, v in emb.items():
    print(isinstance(v, nn.Embedding))

True
True


In [22]:
embedding = nn.Embedding(num_embeddings=1, embedding_dim=64)
nn.init.xavier_uniform_(embedding.weight.data)
# output = embedding(torch.tensor([1, 5, 23]))

tensor([[ 0.0694, -0.1230,  0.0671,  0.0252,  0.0220, -0.0815, -0.1832, -0.1005,
         -0.1546,  0.2799,  0.2589,  0.2228, -0.1455,  0.1143,  0.0578,  0.0966,
          0.2218, -0.0698,  0.2367, -0.1803,  0.2564, -0.2379, -0.1027, -0.1324,
          0.2208,  0.1368, -0.0185, -0.1797,  0.0614,  0.2477, -0.1069, -0.0157,
         -0.0782,  0.2906,  0.2053,  0.0444,  0.2279, -0.2478,  0.2326, -0.1585,
         -0.2865,  0.2828,  0.2448,  0.1065, -0.2918,  0.1287,  0.1107, -0.1876,
         -0.2793,  0.2206,  0.1322,  0.0916, -0.0664,  0.0801,  0.1247,  0.0772,
         -0.2873,  0.0587,  0.0961, -0.0513,  0.1384, -0.1195, -0.1136, -0.2734]])

In [15]:
layer = nn.Linear(4, 2)
print(nn.init.xavier_uniform_(layer.weight))
print(nn.init.constant_(layer.bias, 0))

Parameter containing:
tensor([[-0.8079,  0.0481, -0.1103,  0.4114],
        [ 0.2513,  0.6838, -0.7178, -0.0084]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [24]:
param = nn.Parameter(torch.Tensor(64))
print(param.dim())
nn.init.xavier_uniform_(param.unsqueeze(0)).squeeze(0)


1


tensor([-0.0091,  0.2859, -0.0470, -0.0689, -0.0940,  0.0716, -0.2879, -0.2425,
        -0.2054,  0.1464, -0.2559, -0.2767, -0.1598, -0.1176, -0.2949,  0.0794,
         0.1673,  0.1195, -0.2729, -0.2093,  0.0995, -0.0159, -0.0128,  0.1572,
        -0.0994, -0.2667, -0.0257, -0.0334,  0.2021,  0.1959,  0.2266,  0.0901,
         0.2681,  0.2118, -0.0707, -0.1261,  0.0895, -0.0188, -0.2922, -0.1530,
         0.1195,  0.3005,  0.0671,  0.1845,  0.1561,  0.0206,  0.1967, -0.0624,
         0.0523,  0.0679,  0.2326, -0.2999, -0.0270, -0.2474,  0.1800, -0.0427,
         0.2571, -0.0334, -0.2835,  0.2643,  0.1917,  0.1906, -0.2583,  0.1542],
       grad_fn=<SqueezeBackward1>)