In [2]:
import pandas as pd
import numpy as np
import torch
from torch import nn


In [ ]:
emb = nn.ModuleDict(
    {"a": nn.Embedding(10, 3), "b": nn.Embedding(10, 3)}
)


isinstance(emb, nn.ModuleDict)
for k, v in emb.items():
    print(isinstance(v, nn.Embedding))

True
True


In [22]:
embedding = nn.Embedding(num_embeddings=1, embedding_dim=64)
nn.init.xavier_uniform_(embedding.weight.data)
# output = embedding(torch.tensor([1, 5, 23]))

tensor([[ 0.0694, -0.1230,  0.0671,  0.0252,  0.0220, -0.0815, -0.1832, -0.1005,
         -0.1546,  0.2799,  0.2589,  0.2228, -0.1455,  0.1143,  0.0578,  0.0966,
          0.2218, -0.0698,  0.2367, -0.1803,  0.2564, -0.2379, -0.1027, -0.1324,
          0.2208,  0.1368, -0.0185, -0.1797,  0.0614,  0.2477, -0.1069, -0.0157,
         -0.0782,  0.2906,  0.2053,  0.0444,  0.2279, -0.2478,  0.2326, -0.1585,
         -0.2865,  0.2828,  0.2448,  0.1065, -0.2918,  0.1287,  0.1107, -0.1876,
         -0.2793,  0.2206,  0.1322,  0.0916, -0.0664,  0.0801,  0.1247,  0.0772,
         -0.2873,  0.0587,  0.0961, -0.0513,  0.1384, -0.1195, -0.1136, -0.2734]])

In [15]:
layer = nn.Linear(4, 2)
print(nn.init.xavier_uniform_(layer.weight))
print(nn.init.constant_(layer.bias, 0))

Parameter containing:
tensor([[-0.8079,  0.0481, -0.1103,  0.4114],
        [ 0.2513,  0.6838, -0.7178, -0.0084]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [21]:
# param = nn.Parameter(torch.Tensor(64))
param = nn.Parameter(torch.empty(64))
param = param.unsqueeze(0)
print(param.dim())
print(param)
print(param.size(0))
# print(nn.init.xavier_uniform_(param.unsqueeze(0)).squeeze(0))
# print(nn.init.xavier_normal_(param.unsqueeze(0)).squeeze(0))


2
tensor([[1.4601e+17, 4.1719e-41, 5.4475e+11, 3.4937e-41, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 2.5366e-02, 1.8788e+31, 1.7220e+22,
         2.1715e-18, 8.4642e-07, 4.1961e-08, 1.6766e+22, 1.0524e+21, 2.6514e-09,
         2.6541e+20, 6.7019e-10, 1.0860e-05, 1.7011e-04, 2.6703e-06, 4.3439e-05,
         2.1707e-18, 1.6678e+19, 7.0976e+22, 2.1715e-18, 4.2330e+21, 1.6534e+19,
         1.1625e+27, 1.4580e-19, 7.1856e+22, 4.3605e+27, 1.5766e-19, 2.6330e+20,
         1.4580e-19, 1.8179e+31, 1.8524e+28, 2.1715e-18, 8.4642e-07, 4.1961e-08,
         1.6766e+22, 1.0524e+21, 2.6514e-09, 2.6541e+20, 6.7019e-10, 1.0860e-05,
         1.4580e-19, 7.1429e+31, 1.5766e-19, 1.0256e-08, 2.6252e-06, 3.0785e+12,
         1.0840e-08, 2.5790e-09, 2.6803e-09, 1.2539e+16, 2.1707e-18, 1.9205e+31,
         3.2314e-18, 6.0397e-07, 1.3475e+37, 9.0042e-02]],
       grad_fn=<UnsqueezeBackward0>)
1


In [57]:
import math
p = nn.Parameter(torch.empty(4))
print(p)
with torch.no_grad():
    embed_dim = p.size(0)
    bound = math.sqrt(6 / embed_dim)
    p.normal_(-bound, bound)
print(p)

Parameter containing:
tensor([5.4929e+11, 3.4937e-41, 5.3834e+11, 3.4937e-41], requires_grad=True)
Parameter containing:
tensor([ 0.2471, -2.7944, -2.1335, -1.2309], requires_grad=True)
