In [1]:
import pandas as pd
import numpy as np
import torch
from torch import nn


In [ ]:
from torch_geometric.nn.conv.gcn_conv import gcn_norm
gcn_norm()


In [5]:
from modules.dps_modules import DPSPredictor
from modules.loss import L2Loss
dps_model = DPSPredictor(emb_dim=64, concat_emb=False)
l2_loss = L2Loss()
l2_loss(*dps_model.projection_fcs.values())


tensor(0.7209, grad_fn=<AddBackward0>)

In [22]:
torch.manual_seed(0)
a = torch.rand(3, 8)
user_emb = nn.Parameter(a, requires_grad=True)
print(user_emb)
num_users, dim = user_emb.size()
delta_user_emb = nn.Embedding(num_users, dim)
print(delta_user_emb.weight)
final_user_emb = (user_emb + delta_user_emb.weight)
print(final_user_emb[[1, 2]])
user_emb.requires_grad_(False)
print(user_emb)
user_emb.requires_grad_(True)
print(user_emb)

Parameter containing:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185],
        [0.6977, 0.8000, 0.1610, 0.2823, 0.6816, 0.9152, 0.3971, 0.8742]],
       requires_grad=True)
Parameter containing:
tensor([[ 0.4681, -0.1577,  1.4437,  0.2660,  0.1665,  0.8744, -0.1435, -0.1116],
        [-0.6731,  0.8728,  1.0554,  0.1778, -0.2303, -0.3918,  0.5433, -0.3952],
        [-0.4462,  0.7440,  1.5210,  3.4105, -1.5312, -1.2341,  1.8197, -0.5515]],
       requires_grad=True)
tensor([[-0.2175,  1.5051,  1.4043,  0.5796, -0.2080, -0.2229,  0.8372,  0.1234],
        [ 0.2515,  1.5440,  1.6820,  3.6928, -0.8496, -0.3189,  2.2168,  0.3226]],
       grad_fn=<IndexBackward0>)
Parameter containing:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185],
        [0.6977, 0.8000, 0.1610, 0.2823, 0.6816, 0.9152, 0.3971,

In [2]:
emb = nn.ModuleDict(
    {"a": nn.Embedding(10, 3), "b": nn.Embedding(10, 3)}
)


isinstance(emb, nn.ModuleDict)
for k, v in emb.items():
    print(isinstance(v, nn.Embedding))

True
True


In [22]:
embedding = nn.Embedding(num_embeddings=1, embedding_dim=64)
nn.init.xavier_uniform_(embedding.weight.data)
# output = embedding(torch.tensor([1, 5, 23]))

tensor([[ 0.0694, -0.1230,  0.0671,  0.0252,  0.0220, -0.0815, -0.1832, -0.1005,
         -0.1546,  0.2799,  0.2589,  0.2228, -0.1455,  0.1143,  0.0578,  0.0966,
          0.2218, -0.0698,  0.2367, -0.1803,  0.2564, -0.2379, -0.1027, -0.1324,
          0.2208,  0.1368, -0.0185, -0.1797,  0.0614,  0.2477, -0.1069, -0.0157,
         -0.0782,  0.2906,  0.2053,  0.0444,  0.2279, -0.2478,  0.2326, -0.1585,
         -0.2865,  0.2828,  0.2448,  0.1065, -0.2918,  0.1287,  0.1107, -0.1876,
         -0.2793,  0.2206,  0.1322,  0.0916, -0.0664,  0.0801,  0.1247,  0.0772,
         -0.2873,  0.0587,  0.0961, -0.0513,  0.1384, -0.1195, -0.1136, -0.2734]])

In [15]:
layer = nn.Linear(4, 2)
print(nn.init.xavier_uniform_(layer.weight))
print(nn.init.constant_(layer.bias, 0))

Parameter containing:
tensor([[-0.8079,  0.0481, -0.1103,  0.4114],
        [ 0.2513,  0.6838, -0.7178, -0.0084]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [5]:
# param = nn.Parameter(torch.Tensor(64))
param = nn.Parameter(torch.empty(2, 8))
# param = param.unsqueeze(0)
print(param.dim())
print(param)
print(param.size(0))
print(nn.init.xavier_uniform_(param.unsqueeze(0)).squeeze(0))
# print(nn.init.xavier_normal_(param.unsqueeze(0)).squeeze(0))


2
Parameter containing:
tensor([[-6.8844e-11,  3.1140e-41,  7.9802e-30,  4.4348e-41,  1.4013e-45,
          0.0000e+00,  2.2421e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00]], requires_grad=True)
2
tensor([[ 0.1213,  0.0094, -0.2136,  0.1089,  0.0575,  0.4160, -0.4932,  0.3032],
        [-0.0759,  0.3657, -0.4803,  0.3861,  0.2128, -0.2628,  0.1336, -0.2484]],
       grad_fn=<SqueezeBackward1>)


In [57]:
import math
p = nn.Parameter(torch.empty(4))
print(p)
with torch.no_grad():
    embed_dim = p.size(0)
    bound = math.sqrt(6 / embed_dim)
    p.normal_(-bound, bound)
print(p)

Parameter containing:
tensor([5.4929e+11, 3.4937e-41, 5.3834e+11, 3.4937e-41], requires_grad=True)
Parameter containing:
tensor([ 0.2471, -2.7944, -2.1335, -1.2309], requires_grad=True)


In [4]:
import cvxpy as cp

# Define variables
x = cp.Variable()
y = cp.Variable()

# Define objective
objective = cp.Maximize(x + y)

# Define constraints
constraints = [
    x + y <= 1,
    x >= 0,
    y >= 0
]

# Solve the problem
problem = cp.Problem(objective, constraints)
result = problem.solve()

print("Problem status:", problem.status)
print("Optimal value:", result)
print("x =", x.value)
print("y =", y.value)


Problem status: optimal
Optimal value: 0.9999999992978337
x = 0.4999999996489246
y = 0.4999999996489091


In [ ]:


from post_processing.dpa_rs import DPA_RS

rerank = DPA_RS(
)